/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "secondary-fixed": "#00E5FF",
        "secondary-fixed-dim": "#00A7F2",
        "on-primary": "#000000",
        "inverse-surface": "#ffffff",
        "outline-variant": "#2A2A2A",
        "tertiary": "#DDB7FF",
        "on-tertiary-container": "#DDB7FF",
        "surface-container": "#0E0E0E",
        "on-tertiary-fixed": "#DDB7FF",
        "on-tertiary": "#000000",
        "on-surface-variant": "#E2E2E2",
        "tertiary-dim": "#DDB7FF",
        "tertiary-container": "#2A2A2A",
        "inverse-primary": "#DDB7FF",
        "primary-container": "#1A1A1A",
        "inverse-on-surface": "#000000",
        "on-secondary": "#000000",
        "surface-bright": "#1A1A1A",
        "on-surface": "#E2E2E2",
        "tertiary-fixed": "#DDB7FF",
        "on-secondary-container": "#00E5FF",
        "error-dim": "#d73357",
        "primary": "#DDB7FF",
        "on-tertiary-fixed-variant": "#DDB7FF",
        "error": "#ff6e84",
        "primary-dim": "#B68CFF",
        "primary-fixed-dim": "#B68CFF",
        "secondary-dim": "#00A7F2",
        "on-primary-fixed": "#000000",
        "error-container": "#a70138",
        "on-background": "#E2E2E2",
        "on-primary-fixed-variant": "#000000",
        "primary-fixed": "#DDB7FF",
        "surface-container-high": "#1A1A1A",
        "on-secondary-fixed-variant": "#00E5FF",
        "secondary-container": "#002a42",
        "surface": "#000000",
        "background": "#000000",
        "tertiary-fixed-dim": "#DDB7FF",
        "surface-dim": "#000000",
        "surface-container-highest": "#222222",
        "on-error": "#ffffff",
        "surface-container-low": "#0E0E0E",
        "on-error-container": "#ffb2b9",
        "on-secondary-fixed": "#000000",
        "secondary": "#00E5FF",
        "surface-tint": "#DDB7FF",
        "outline": "#444444",
        "surface-variant": "#1A1A1A",
        "on-primary-container": "#DDB7FF"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
